language: node_js
node_js:
  - 12
script:
  npm test && npm run build

deploy:
  provider: pages
  repo: gestor-psa/gestor-psa.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master
